# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'process_list.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_dlgProcessList(object):
    def setupUi(self, dlgProcessList):
        dlgProcessList.setObjectName("dlgProcessList")
        dlgProcessList.resize(290, 481)
        self.verticalLayout = QtWidgets.QVBoxLayout(dlgProcessList)
        self.verticalLayout.setObjectName("verticalLayout")
        self.listWidget = QtWidgets.QListWidget(dlgProcessList)
        self.listWidget.setObjectName("listWidget")
        self.verticalLayout.addWidget(self.listWidget)
        self.buttonBox = QtWidgets.QDialogButtonBox(dlgProcessList)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(dlgProcessList)
        self.buttonBox.accepted.connect(dlgProcessList.accept)
        self.buttonBox.rejected.connect(dlgProcessList.reject)
        QtCore.QMetaObject.connectSlotsByName(dlgProcessList)

    def retranslateUi(self, dlgProcessList):
        _translate = QtCore.QCoreApplication.translate
        dlgProcessList.setWindowTitle(_translate("dlgProcessList", "Dialog"))
